### PR TITLE
add colors for nested json

### PR DESCRIPTION
**Pull request by byFd**
as i recently came back to use cobalt i noticed the lack of nested json highlighting (as already mentioned in #48)
got the nesting stuff from https://github.com/MattDMo/Neon-color-scheme
colors repeat after 6 nestings deep until 18 deep
i tried to pick suitable colors from the already used colors in the theme file

### CODE REVIEW

**Comment by wesbos** [comment]
Ohh this is awesome  - do you have a screenshot before I merge it?

**Comment by byFd** [comment]
image
colors could use some finetuning i guess, but i'm not too good at that :)
atleast it offers some more readability imho

**Comment by benfavre** [comment]
YES !

**Comment by wesbos** [comment]
So - I'm not sure I like the feel of this just yet. 

To me, colours in Sublime mean that they are different things - I use indentation and the indentation guides  (http://wesbos.com/sublime-text-indentation-guide-lines/) 

I asked on twitter and I'm getting some good feedback too. 

https://twitter.com/wesbos/status/656826553158926336

**Comment by byFd** [comment]
Ok, i get your point.
I'll see how i can do only different colors for keys and values.

**Comment by reintroducing** [comment]
@byFd Did you ever get the key/value different colors working? I love everything about this theme except the fact that my JSON files are all green :\

**Comment by Ganbin** [comment]
I add my vote, not to have different colour for every new indentation (which is obvious for me). But to have a different colour for key / value. Maybe a new vote in twitter is required? :-)

**Pull request closed without merging**
